server:
  port: 8081
  servlet:
    context-path: /myapp

#配置thymeleaf的配置
#开发阶段的缓存设为false方便调试, 上线后社会true提高效率
spring:
  thymeleaf:
    cache: false
    #设置模板的路径后缀
    prefix: classpath:/templates/
    #设置模板的后缀
    suffix: .html
    #设置模板的类型
    mode: HTML